# Numpy


Numpy is a python library which is used for doing mathematical opeartions on arrays

In [1]:
import numpy as np

In [2]:
l = [1,2,3,4,5]

In [3]:
arr = np.array(l)

In [4]:
arr

array([1, 2, 3, 4, 5])

In [5]:
type(arr)  ## ndarray array means it is an n dimensional array 

numpy.ndarray

In [6]:
np.asarray(l)

array([1, 2, 3, 4, 5])

In [7]:
arr1 = np.array([[1,2,3] , [4,5,6]])

In [8]:
arr.ndim  ## This is used to give the dimension of the array

1

In [9]:
arr1.ndim

2

In [10]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
mat=np.matrix(l)  ## This will give the matrix habving minimum dimension of 2

Matrix is basically a subclass of array

In [12]:
np.asanyarray(l)  ## asanyarray is a function which is used to create any parameter into an array. But it unable to convert matrix into an array because matrix is a sub class of array. 

array([1, 2, 3, 4, 5])

In [13]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4, 5]])

## Solo copy  

In a solo copy it is not copying the array entirely but giving the new reference.

In [14]:
a=arr

In [15]:
a

array([1, 2, 3, 4, 5])

In [16]:
arr[0]=100

In [17]:
arr

array([100,   2,   3,   4,   5])

In [18]:
a

array([100,   2,   3,   4,   5])

In the above example as you change the a then arr also changes

## copy

In [19]:
b = np.copy(arr)  ## In a copy a new data set of arr is created and whatever change in b will not going to affect the previous one

In [20]:
b

array([100,   2,   3,   4,   5])

In [21]:
b[0]= 50

In [22]:
b

array([50,  2,  3,  4,  5])

In [23]:
arr

array([100,   2,   3,   4,   5])

In [24]:
np.fromfunction(lambda i,j: (i==j), (4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [25]:
np.fromfunction(lambda i,j: (i*j), (4,4))

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.],
       [0., 3., 6., 9.]])

In [26]:
list(i*i for i in range(5)) 

[0, 1, 4, 9, 16]

In [27]:
sq = (i*i for i in range(5))

In [28]:
np.fromiter(sq,float) ## it converts into array by iteration

array([ 0.,  1.,  4.,  9., 16.])

In [29]:
np.fromstring('12 14 15', sep=' ')

array([12., 14., 15.])

In [30]:
np.fromstring('12,14,15', sep=',')

array([12., 14., 15.])

In [31]:
arr

array([100,   2,   3,   4,   5])

In [32]:
arr.ndim

1

In [33]:
arr.size

5

In [34]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
arr1.ndim

2

In [36]:
arr1.size

6

In [37]:
list(range(5))

[0, 1, 2, 3, 4]

In [38]:
list(range(5,15,2))

[5, 7, 9, 11, 13]

In [40]:
list(range(0.55,15,2))  ## it giving error because range function can never be a floating value

TypeError: 'float' object cannot be interpreted as an integer

In [41]:
## for making a floating number  ## it will start from 0.2 and goes upto 10 with the skip of 0.4
np.arange(0.2,10,0.4)


array([0.2, 0.6, 1. , 1.4, 1.8, 2.2, 2.6, 3. , 3.4, 3.8, 4.2, 4.6, 5. ,
       5.4, 5.8, 6.2, 6.6, 7. , 7.4, 7.8, 8.2, 8.6, 9. , 9.4, 9.8])

In [42]:
list(np.arange(0.2,10,0.4))

[0.2,
 0.6000000000000001,
 1.0000000000000002,
 1.4000000000000001,
 1.8000000000000003,
 2.2000000000000006,
 2.6000000000000005,
 3.000000000000001,
 3.400000000000001,
 3.8000000000000007,
 4.200000000000001,
 4.600000000000001,
 5.000000000000001,
 5.400000000000001,
 5.800000000000002,
 6.200000000000001,
 6.600000000000001,
 7.000000000000002,
 7.400000000000001,
 7.800000000000002,
 8.200000000000001,
 8.600000000000001,
 9.000000000000002,
 9.4,
 9.8]

In [43]:
np.linspace(1,2,20)  ## it will going to find the value between 1 and 2 into 20 parts equally

array([1.        , 1.05263158, 1.10526316, 1.15789474, 1.21052632,
       1.26315789, 1.31578947, 1.36842105, 1.42105263, 1.47368421,
       1.52631579, 1.57894737, 1.63157895, 1.68421053, 1.73684211,
       1.78947368, 1.84210526, 1.89473684, 1.94736842, 2.        ])

In [44]:
np.logspace(1,5,10,base=2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [45]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [46]:
np.zeros((3,4,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [47]:
np.ones(4)

array([1., 1., 1., 1.])

In [48]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [49]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [50]:
import pandas as pd

In [51]:
pd.DataFrame(np.eye(5), index = ['a','b','c','d','e'],columns=['df','de','gt','hy','vv'])

df   de   gt   hy   vv
a  1.0  0.0  0.0  0.0  0.0
b  0.0  1.0  0.0  0.0  0.0
c  0.0  0.0  1.0  0.0  0.0
d  0.0  0.0  0.0  1.0  0.0
e  0.0  0.0  0.0  0.0  1.0

In [52]:
np.random.rand(3,3)  ## random.rand  gives the array of any number of given range

array([[0.26291522, 0.67382787, 0.97003422],
       [0.63209302, 0.24610185, 0.49511758],
       [0.28266943, 0.81426003, 0.90374238]])

In [53]:
np.random.randn(3,3)   ## random.rand  gives the array of any number of given range but its mean and std deviation is always one

array([[-1.62210344, -0.97921337, -0.00640053],
       [-0.7432113 , -0.70975216,  0.4618365 ],
       [-1.05686082,  0.29591855, -0.30057031]])

In [54]:
arr2=np.random.randint(7,9, (4,4)) ## it will give the matrix of 4x4 whose all values lies between 7 and 9

In [55]:
np.empty((3,3))


array([[1.62210344, 0.97921337, 0.00640053],
       [0.7432113 , 0.70975216, 0.4618365 ],
       [1.05686082, 0.29591855, 0.30057031]])

In [56]:
arr2

array([[8, 7, 7, 8],
       [8, 7, 8, 7],
       [7, 8, 7, 8],
       [7, 8, 7, 7]])

In [57]:
arr2.size

16

In [58]:
arr2.shape

(4, 4)

In [59]:
arr2.reshape(2,8)

array([[8, 7, 7, 8, 8, 7, 8, 7],
       [7, 8, 7, 8, 7, 8, 7, 7]])

In [60]:
arr2.reshape(8,2)

array([[8, 7],
       [7, 8],
       [8, 7],
       [8, 7],
       [7, 8],
       [7, 8],
       [7, 8],
       [7, 7]])

In [61]:
arr3=np.random.randint(1,10,(4,5))

In [62]:
arr3

array([[1, 2, 6, 4, 9],
       [1, 4, 8, 1, 1],
       [6, 9, 3, 1, 3],
       [3, 6, 8, 4, 4]])

In [63]:
arr3 >8

array([[False, False, False, False,  True],
       [False, False, False, False, False],
       [False,  True, False, False, False],
       [False, False, False, False, False]])

In [64]:
arr3[arr3>7]

array([9, 8, 9, 8])

In [65]:
## Extraction of data from array and finding its position
arr3[3,[1,2,4]]

array([6, 8, 4])

In [66]:
arr3[1:3,[2,4]]

array([[8, 1],
       [3, 3]])

In [67]:
arr4 = np.random.randint(1,3,(4,4))
arr5 = np.random.randint(1,3,(4,4))

In [68]:
arr4

array([[2, 2, 1, 1],
       [2, 1, 2, 1],
       [1, 2, 1, 2],
       [1, 1, 1, 1]])

In [69]:
arr5

array([[2, 1, 1, 2],
       [1, 2, 1, 2],
       [1, 2, 1, 1],
       [1, 1, 2, 2]])

In [70]:
arr4 + arr5

array([[4, 3, 2, 3],
       [3, 3, 3, 3],
       [2, 4, 2, 3],
       [2, 2, 3, 3]])

In [71]:
arr4 * arr5  ## this is doing index multiplication

array([[4, 2, 1, 2],
       [2, 2, 2, 2],
       [1, 4, 1, 2],
       [1, 1, 2, 2]])

In [72]:
## for matrix multiplication

arr4@arr5

array([[ 8,  9,  7, 11],
       [ 8,  9,  7, 10],
       [ 7,  9,  8, 11],
       [ 5,  6,  5,  7]])

In [73]:
arr4/arr5

array([[1. , 2. , 1. , 0.5],
       [2. , 0.5, 2. , 0.5],
       [1. , 1. , 1. , 2. ],
       [1. , 1. , 0.5, 0.5]])

In [74]:
arr4/0

/tmp/ipykernel_188/1674986024.py:1: RuntimeWarning: divide by zero encountered in divide
  arr4/0


array([[inf, inf, inf, inf],
       [inf, inf, inf, inf],
       [inf, inf, inf, inf],
       [inf, inf, inf, inf]])

In [75]:
arr6 = np.zeros((4,4))

In [76]:
arr6

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [77]:
arr6 + 5



array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [78]:
a= np.array([3,4,5])

In [79]:
a+arr1

array([[ 4,  6,  8],
       [ 7,  9, 11]])

In [80]:
np.sqrt(a)

array([1.73205081, 2.        , 2.23606798])

In [81]:
np.exp(a)

array([ 20.08553692,  54.59815003, 148.4131591 ])

In [82]:
np.min(a)

3

In [83]:
np.max(arr1)

6

## Array manipulation

In [84]:
arr7=np.random.randint(1,10, (4,4))

In [85]:
arr7

array([[3, 9, 4, 7],
       [7, 2, 3, 2],
       [6, 5, 3, 4],
       [8, 8, 7, 1]])

In [86]:
arr7.reshape(1,16)

array([[3, 9, 4, 7, 7, 2, 3, 2, 6, 5, 3, 4, 8, 8, 7, 1]])

In [87]:
arr7.T

array([[3, 7, 6, 8],
       [9, 2, 5, 8],
       [4, 3, 3, 7],
       [7, 2, 4, 1]])

In [88]:
arr7.flatten()  ## It will going to convert the array into one_dimensonal array

array([3, 9, 4, 7, 7, 2, 3, 2, 6, 5, 3, 4, 8, 8, 7, 1])

In [89]:
arr7

array([[3, 9, 4, 7],
       [7, 2, 3, 2],
       [6, 5, 3, 4],
       [8, 8, 7, 1]])

In [90]:
np.expand_dims(arr7,axis=1) ## It will going to increase the dimensions of array..and axis=1 means expansion in rowwise

array([[[3, 9, 4, 7]],

       [[7, 2, 3, 2]],

       [[6, 5, 3, 4]],

       [[8, 8, 7, 1]]])

In [91]:
np.expand_dims(arr7,axis=0 ) ## expansion in row wise

array([[[3, 9, 4, 7],
        [7, 2, 3, 2],
        [6, 5, 3, 4],
        [8, 8, 7, 1]]])

In [92]:
arr8=np.array([[1],[2],[3]])

In [93]:
arr8.ndim

2

In [94]:
arr9=np.squeeze(arr8)


In [95]:
arr9

array([1, 2, 3])

In [96]:
arr9.ndim  ## squeeze function going to reduce the dimension of the array

1

In [97]:
np.repeat(arr9,3) ## it is going to repeat the array into 3 times

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [98]:
arr9

array([1, 2, 3])

In [99]:
np.roll(arr9,1) ## it means that the array is going to roll one step forward one time   

array([3, 1, 2])

In [100]:
np.diag(np.array([1,2,3,4]))  ## it will going to give diagonally the result

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

## Binary operation

In [101]:
arr10 = np.random.randint(1,10,(3,4))
arr11 = np.random.randint(1,10,(3,4))

In [102]:
arr10

array([[9, 4, 1, 7],
       [2, 9, 7, 3],
       [4, 4, 8, 1]])

In [103]:
arr11

array([[8, 1, 9, 7],
       [1, 9, 6, 3],
       [1, 4, 7, 4]])

In [104]:
arr10**arr11

array([[ 43046721,         4,         1,    823543],
       [        2, 387420489,    117649,        27],
       [        4,       256,   2097152,         1]])

In [105]:
arr10>arr11

array([[ True,  True, False, False],
       [ True, False,  True, False],
       [ True, False,  True, False]])

## String Function

In [106]:
arr12 = np.array(["akash","roy"])

In [107]:
arr12

array(['akash', 'roy'], dtype='<U5')

In [108]:
np.char.upper(arr12)

array(['AKASH', 'ROY'], dtype='<U5')

In [109]:
np.char.capitalize(arr12)

array(['Akash', 'Roy'], dtype='<U5')

In [110]:
np.char.title(arr12)

array(['Akash', 'Roy'], dtype='<U5')

## Mathematical operation

In [111]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [112]:
np.sin(arr1)   ## sine value of each  index

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ]])

In [113]:
np.cos(arr1)

array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029]])

In [114]:
np.power(arr1,3)

array([[  1,   8,  27],
       [ 64, 125, 216]])

In [115]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [116]:
np.mean(arr1)

3.5

In [117]:
np.median(arr1)

3.5

In [118]:
np.std(arr1)

1.707825127659933

In [119]:
np.var(arr1)

2.9166666666666665

In [120]:
np.min(arr1)

1

In [121]:
np.max(arr1)

6

In [122]:
arr11-arr10

array([[-1, -3,  8,  0],
       [-1,  0, -1,  0],
       [-3,  0, -1,  3]])

In [123]:
np.mean(arr1)

3.5

## Searching sorting and counting functions

In [124]:
arr13 = np.array([1,2,3,4,5,6,7,8,9,0])

In [125]:
arr13

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [126]:
np.sort(arr13)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [127]:
np.searchsorted(arr13,7) ## This is saying that where to insert int 7 so that the array will be sorted one

6

In [128]:
np.count_nonzero(arr13) ## It will going to count the numbers of non zero elements

9

In [129]:
arr14 = np.array([0,55,73,9,0,0,22,-3,0,5,0,5,0])

In [130]:
arr14

array([ 0, 55, 73,  9,  0,  0, 22, -3,  0,  5,  0,  5,  0])

In [131]:
np.where(arr14<0)  ## It will going to find out the indexes according to the condition

(array([7]),)

In [132]:
np.extract(arr14>22,arr14)   ## It will going to find out the values according to the condition

array([55, 73])

## Byte swap

In [133]:
arr14.byteswap()

array([                  0, 3963167672086036480, 5260204364768739328,
        648518346341351424,                   0,                   0,
       1585267068834414592, -144115188075855873,                   0,
        360287970189639680,                   0,  360287970189639680,
                         0])

## matrix library

In [134]:
import numpy.matlib as nm

In [135]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [136]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [137]:
nm.zeros((4,5))


matrix([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [138]:
nm.eye(4)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

## Linear Algebra

In [139]:
arr15 = np.array([])

In [140]:
arr10

array([[9, 4, 1, 7],
       [2, 9, 7, 3],
       [4, 4, 8, 1]])

In [141]:
arr11

array([[8, 1, 9, 7],
       [1, 9, 6, 3],
       [1, 4, 7, 4]])

In [143]:
np.multiply(arr10,arr11)

array([[72,  4,  9, 49],
       [ 2, 81, 42,  9],
       [ 4, 16, 56,  4]])

In [144]:
arr10 * arr11

array([[72,  4,  9, 49],
       [ 2, 81, 42,  9],
       [ 4, 16, 56,  4]])

In [145]:
arrx=np.random.randint(1,10,(2,2))

In [146]:
arrx

array([[7, 5],
       [1, 3]])